---
home-assistant:
  build: Dockerfile-rpi
  restart: always
  net: "host"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
    - '/etc/home-assistant/hadashboard/dashboards:/app/dashboards
    - '/etc/home-assistant/hadashboard/config/:/app/lib/
    - '/etc/home-assistant/hadashboard/hapush/:/app/hapush/

